export default {
  // new
  // activities components state
  numberOfWorkshops: 0,
  photolikingPickDateChecked: false,
  photoshootPickDateChecked: false,
  paymentsPickDateChecked: [],
  workshopPickDateChecked: [],
  otherActivitiesPickDateChecked: [],
  selectFinalEventLocation: '',
  selectOtherActivityLocation: [],
  selectWorkshopLocation: [],
  selectPhotoshootLocation: '',
  selectOrientationLocation: '',
  orientation: {
    startDate: '',
    endDate: '',
    time: 'Sat Jan 12 2019 08:00:00',
    location: '',
    details: '',
    eventKey: '',
    id: ``,
    title: `Orientation`,
    actType: 'detailed',
    type: 'orientation',
    classes: ''
  },
  paymentsAmount: [],
  payments: {
    startDate: [],
    endDate: [],
    eventKey: [],
    id: [],
    title: [],
    actType: '',
    type: [],
    classes: [],
    amount: []
  },
  photoshoot: {
    startDate: '',
    endDate: '',
    time: "Sat Jan 12 2019 08:00:00",
    location: '',
    details: '',
    eventKey: '',
    id: ``,
    title: '',
    actType: 'detailed',
    type: 'photoshoot',
    classes: ''
  },
  photoliking: {
    startDate: '',
    endDate: '',
    time: '',
    location: '',
    details: '',
    eventKey: '',
    id: '',
    title: '',
    type: 'photoliking',
    actType: 'date range',
    classes: ''
  },
  workshops: {
    startDate: [],
    endDate: [],
    time: [],
    location: [],
    details: [],
    eventKey: [],
    id: [],
    title: [],
    actType: [],
    type: [],
    classes: []
  },
  otherActivities: {
    startDate: [],
    endDate: [],
    time: [],
    location: [],
    details: [],
    eventKey: [],
    id: [],
    title: [],
    type: [],
    actType: [],
    classes: []
  },
  finalEvent: {
    startDate: '',
    endDate: '',
    time: 'Sat Jan 12 2019 08:00:00',
    location: '',
    details: '',
    eventKey: '',
    id: '',
    title: `Final Event`,
    type: 'final event',
    actType: 'detailed',
    classes: ''
  },
  // activityPreview Components states
  plottedActivities: [],
  tempSeasonDraft: {},
  editBatchModal: false,
  newCourseModal: false,
  uploadNewSeasonBatchesModal: false,
  excelData: {
    headers: [],
    tickets: []
  },

  // old
  events: [],
  event: {},
  eventSeasonNumber: '',
  evetnSeasonName: '',
  batches: [],
  batchNumber: 0,
  colorCode: '',
  isColorCode: false,
  activities: [],
  allActivities: [],
  mergeSchedules: [],
  isViewAllSched: false,
  amountRemaining: 0,
  taskList2: [],
  taskList: [
    { label: 'Orientation', value: 'orientation', visible: true},
    { label: 'Payment', value: 'payment', visible: true},
    { label: 'Photoshoot', value: 'photoshoot', visible: true},
    { label: 'PhotoLiking', value: 'photoliking', visible: true},
    { label: 'Workshop', value: 'workshop', visible: true},
    { label: 'General Rehersal', value: 'generalRehersal', visible: true},
    { label: 'Final Rehersal', value: 'finalRehersal', visible: true}
  ],
  colorOpt: [
  	{ label: 'Pastel Pink', value: 'pastelpink', icon: 'label', leftColor: 'pink-3', visible: true},
  	{ label: 'Pastel Red', value: 'pastelred', icon: 'label', leftColor: 'red-3', visible: true},
  	{ label: 'Pastel Purple', value: 'pastelpurple', icon: 'label', leftColor: 'purple-3', visible: true},
  	{ label: 'Pastel Lavender', value: 'pastellavender', icon: 'label', leftColor: 'purple-4', visible: true},
  	{ label: 'Pastel Orange', value: 'pastelorange', icon: 'label', leftColor: 'orange-4', visible: true},
  	{ label: 'Pastel Yellow', value: 'pastelyellow', icon: 'label', leftColor: 'yellow-4', visible: true},
  	{ label: 'Pastel Green', value: 'pastelgreen', icon: 'label', leftColor: 'light-green-4', visible: true},
    { label: 'Pastel Blue', value: 'pastelblue', icon: 'label', leftColor: 'cyan-3', visible: true},
    { label: 'Shades of Gray', value: 'shadesofgray', icon: 'label', leftColor: 'grey-5', visible: true},
    { label: 'Shades of Green', value: 'shadesofgreen', icon: 'label', leftColor: 'green-8', visible: true},
    { label: 'Shades of Blue', value: 'shadesofblue', icon: 'label', leftColor: 'teal-5', visible: true},
    { label: 'Shades of Pink', value: 'shadesofpink', icon: 'label', leftColor: 'pink-6', visible: true},
    { label: 'Dark Purple', value: 'darkpurple', icon: 'label', leftColor: 'deep-purple-5', visible: true},
    { label: 'Lime Green', value: 'limegreen', icon: 'label', leftColor: 'light-green-14', visible: true},
    { label: 'Olive', value: 'olive', icon: 'label', leftColor: 'green-8', visible: true},
    { label: 'Salad Yellow', value: 'saladyellow', icon: 'label', leftColor: 'amber-6', visible: true},
    { label: 'Yellow', value: 'yellow', icon: 'label', leftColor: 'warning', visible: true},
    { label: 'White Blue', value: 'whiteblue', icon: 'label', leftColor: 'light-blue-4', visible: true},
    { label: 'Orange', value: 'orange', icon: 'label', leftColor: 'orange-5', visible: true},
    { label: 'Pink', value: 'pink', icon: 'label', leftColor: 'pink', visible: true}
  ],
  newBatchModal: false,
  isCreateNewBatch: false,
  activityList: [
  	{ label: 'Orientation', value: 'orientation'},
  	{ label: 'Payment', value: 'payment'},
  	{ label: 'Photoshoot', value: 'photoshoot'},
  	{ label: 'PhotoLiking', value: 'photoliking'},
  	{ label: 'Workshop', value: 'workshop'},
  	{ label: 'General Rehersal', value: 'generalRehersal'},
  	{ label: 'Final Rehersal', value: 'finalRehersal'}
  ]
}
